//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAST.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo4 {
            get {
                object obj = ResourceManager.GetObject("logo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t1.metric_id diag_id, o.object_id object_id, o.object_full_name object_name, t1.metric_name diag_name, count(*) violations_count
        ///FROM dss_metric_results r,
        ///dss_metric_type_trees tt,
        ///dss_metric_types t1,
        ///dss_objects o,
        ///dss_links l,
        ///dss_module_links ml,
        ///dss_objects op,
        ///dss_snapshots s
        ///WHERE tt.metric_id = r.metric_id 
        ///AND tt.metric_parent_id = t1.metric_id 
        ///AND t1.metric_group = 1
        ///AND r.object_id = o.object_id 
        ///AND l.next_object_id = o.object_id 
        ///AND l.previous_object_id = ml.module_id
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Query1 {
            get {
                return ResourceManager.GetString("Query1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     
        ///           rp.Path
        ///FROM       DSS_OBJECTS art
        ///           JOIN DSS_TRANSLATION_TABLE dtt
        ///           ON         dtt.OBJECT_ID = art.OBJECT_ID
        ///           JOIN       :KB.ObjFilRef ofr
        ///           ON         ofr.IdObj     = dtt.SITE_OBJECT_ID
        ///           JOIN       :KB.RefPath rp
        ///           ON         rp.IdFilRef   = ofr.IdFilRef
        ///WHERE 
        ///          art.OBJECT_ID = :ID
        ///
        ///
        ///.
        /// </summary>
        internal static string Query2 {
            get {
                return ResourceManager.GetString("Query2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     
        ///           object_fullname
        ///FROM       :KB.csv_file_objects 
        ///          .
        /// </summary>
        internal static string Query3 {
            get {
                return ResourceManager.GetString("Query3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///t1.metric_id diag_id, 
        ///o.object_id object_id, 
        ///o.object_full_name object_name, 
        ///(SELECT     
        ///           rp.Path
        ///FROM       DSS_OBJECTS art
        ///           JOIN DSS_TRANSLATION_TABLE dtt
        ///           ON         dtt.OBJECT_ID = art.OBJECT_ID
        ///           JOIN       :KB.ObjFilRef ofr
        ///           ON         ofr.IdObj     = dtt.SITE_OBJECT_ID
        ///           JOIN       :KB.RefPath rp
        ///           ON         rp.IdFilRef   = ofr.IdFilRef
        ///WHERE 
        ///          art.OBJECT_ID = o.object_id and rownum=1) file_path,    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Query4 {
            get {
                return ResourceManager.GetString("Query4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t1.metric_id diag_id, o.object_id object_id
        ///FROM dss_metric_results r,
        ///dss_metric_type_trees tt,
        ///dss_metric_types t1,
        ///dss_objects o,
        ///dss_links l,
        ///dss_module_links ml,
        ///dss_objects op,
        ///dss_snapshots s
        ///WHERE tt.metric_id = r.metric_id 
        ///AND tt.metric_parent_id = t1.metric_id 
        ///AND t1.metric_group = 1
        ///AND r.object_id = o.object_id 
        ///AND l.next_object_id = o.object_id 
        ///AND l.previous_object_id = ml.module_id
        ///AND ml.object_id = op.object_id
        ///AND ml.object_type_id = 20000
        ///AND ml.snapshot_id = s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Query5 {
            get {
                return ResourceManager.GetString("Query5", resourceCulture);
            }
        }
    }
}
