//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastServiceClient.CASTServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASTRequestType", Namespace="http://schemas.datacontract.org/2004/07/CAST")]
    [System.SerializableAttribute()]
    public partial class CASTRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VPRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMB {
            get {
                return this.AMBField;
            }
            set {
                if ((object.ReferenceEquals(this.AMBField, value) != true)) {
                    this.AMBField = value;
                    this.RaisePropertyChanged("AMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APP {
            get {
                return this.APPField;
            }
            set {
                if ((object.ReferenceEquals(this.APPField, value) != true)) {
                    this.APPField = value;
                    this.RaisePropertyChanged("APP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDT {
            get {
                return this.CDTField;
            }
            set {
                if ((object.ReferenceEquals(this.CDTField, value) != true)) {
                    this.CDTField = value;
                    this.RaisePropertyChanged("CDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHS {
            get {
                return this.CHSField;
            }
            set {
                if ((object.ReferenceEquals(this.CHSField, value) != true)) {
                    this.CHSField = value;
                    this.RaisePropertyChanged("CHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDA {
            get {
                return this.IDAField;
            }
            set {
                if ((object.ReferenceEquals(this.IDAField, value) != true)) {
                    this.IDAField = value;
                    this.RaisePropertyChanged("IDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDR {
            get {
                return this.IDRField;
            }
            set {
                if ((object.ReferenceEquals(this.IDRField, value) != true)) {
                    this.IDRField = value;
                    this.RaisePropertyChanged("IDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LSV {
            get {
                return this.LSVField;
            }
            set {
                if ((object.ReferenceEquals(this.LSVField, value) != true)) {
                    this.LSVField = value;
                    this.RaisePropertyChanged("LSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAC {
            get {
                return this.MACField;
            }
            set {
                if ((object.ReferenceEquals(this.MACField, value) != true)) {
                    this.MACField = value;
                    this.RaisePropertyChanged("MAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAT {
            get {
                return this.MATField;
            }
            set {
                if ((object.ReferenceEquals(this.MATField, value) != true)) {
                    this.MATField = value;
                    this.RaisePropertyChanged("MAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNN {
            get {
                return this.SNNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNNField, value) != true)) {
                    this.SNNField = value;
                    this.RaisePropertyChanged("SNN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAT {
            get {
                return this.TATField;
            }
            set {
                if ((object.ReferenceEquals(this.TATField, value) != true)) {
                    this.TATField = value;
                    this.RaisePropertyChanged("TAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VBS {
            get {
                return this.VBSField;
            }
            set {
                if ((object.ReferenceEquals(this.VBSField, value) != true)) {
                    this.VBSField = value;
                    this.RaisePropertyChanged("VBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VER {
            get {
                return this.VERField;
            }
            set {
                if ((object.ReferenceEquals(this.VERField, value) != true)) {
                    this.VERField = value;
                    this.RaisePropertyChanged("VER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VPR {
            get {
                return this.VPRField;
            }
            set {
                if ((object.ReferenceEquals(this.VPRField, value) != true)) {
                    this.VPRField = value;
                    this.RaisePropertyChanged("VPR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASTResponseType", Namespace="http://schemas.datacontract.org/2004/07/CAST")]
    [System.SerializableAttribute()]
    public partial class CASTResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGGIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODICE {
            get {
                return this.CODICEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODICEField, value) != true)) {
                    this.CODICEField = value;
                    this.RaisePropertyChanged("CODICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MESSAGGIO {
            get {
                return this.MESSAGGIOField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGGIOField, value) != true)) {
                    this.MESSAGGIOField = value;
                    this.RaisePropertyChanged("MESSAGGIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CAST/Service", ConfigurationName="CASTServiceReference.ICASTService")]
    public interface ICASTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAST/Service/ICASTService/Call", ReplyAction="http://CAST/Service/ICASTService/CallResponse")]
        CastServiceClient.CASTServiceReference.CASTResponseType Call(CastServiceClient.CASTServiceReference.CASTRequestType request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICASTServiceChannel : CastServiceClient.CASTServiceReference.ICASTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CASTServiceClient : System.ServiceModel.ClientBase<CastServiceClient.CASTServiceReference.ICASTService>, CastServiceClient.CASTServiceReference.ICASTService {
        
        public CASTServiceClient() {
        }
        
        public CASTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CASTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CastServiceClient.CASTServiceReference.CASTResponseType Call(CastServiceClient.CASTServiceReference.CASTRequestType request) {
            return base.Channel.Call(request);
        }
    }
}
